server {
    server_name myyt.isaac770.live;

    root /var/www/html;
    index myyt.html index.htm;

    location / {
        add_header Content-Type text/html;

        # Open Graph meta tags
        add_header og:title "My YT Channels";
        add_header og:type "website";
        add_header og:url "https://myyt.isaac770.live/";
        add_header og:image "https://www.isaac770.live/media/myyt-og.png";
        add_header og:description "יחי אדוננו מורנו ורבנו מלך המשיח לעולם ועד";

        try_files $uri $uri/ /myyt.html;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/myyt.isaac770.live/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myyt.isaac770.live/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot




}

